### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by empenguinxh** [TauferLab/NHANES-Analytics#2]
https://github.com/TauferLab/NHANES-Analytics/blob/3d18a7a82313e7ff244cab1db22e527746d59400/src/preprocess.py#L120

It seems that for some data files, `x[mc]` will evaluate as a None type and then the `int()` operation will raise an ValueError.

`spark-submit preprocess.py` with option `--no-mc` will bypass the "if" branch where the above code is executed.

**Comment by mrwyattii** [comment]
The issue was caused when the value stored at x[mc] was a string in scientific notation (e.g., 3e0).  This issue has been resolved with the most recent code push.
